export const ADMIN_ROUTE = '/admin'
export const REGISTRATION_ROUTE = '/registration'
export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '/'
export const MATERIAL_ROUTE = '/material'
export const PROFILE_ROUTE = '/profile'
export const USER_MATERIALS = '/user_materials'